### PR TITLE
Add `exclude` option to pylsp-mypy configuration

### PR DESCRIPTION
**Pull request by maerteijn**

### CODE REVIEW

**Comment by Richardk2n** [comment]
Please format the files using black.

**Comment by maerteijn** [comment]
@Richardk2n I just formatted the files with black (there was indeed an error) and I squashed the commit. 

The PR should pass flake8/black/isort now.

**Comment by maerteijn** [comment]
I’ll see what I can do, I will update the PR soon(ish) and let you know!

**Comment by maerteijn** [comment]
@Richardk2n I've enabled the test runners on my fork now too so I could do a little "remote windows debugging" (aka print statements and look at the github actions output 😉). 

Windows paths are indeed be a bit tricky with `c:\\a` because then `\a` will be seen as a special character and not as a literal character stream. With a raw string `r"c:\\a"` you would solve this, but this can only be defined at parse time and is not usable for already assigned string variables. (You can't mark an existing string variable as a "raw string")

A trick to match this (and other _real_ unicode characters) is is to encode all "special" characters with the `unicode_escape` encoding (and decode back to unicode) to use as input for the `re.match` or `re.search`:

```python
>>> path = 'd:\\a\\pylsp-mypy\\pylsp-mypy\\test\\test_plugin.py'
>>> pattern = path.encode("unicode_escape").decode()
>>> pattern
'd:\\\\a\\\\pylsp-mypy\\\\pylsp-mypy\\\\test\\\\test_plugin.py'
```

This pattern will now math the original path:
```python
re.search(pattern, path)
<re.Match object; span=(0, 46), match='d:\\a\\pylsp-mypy\\pylsp-mypy\\test\\test_plugin.>
```

This is what I implemented now and I added an extra test to verify the pattern matching. See:
- https://github.com/maerteijn/pylsp-mypy/blob/10cbf6b5574f49c4de4da48bb0055d5249930259/pylsp_mypy/plugin.py#L145-L160
- https://github.com/maerteijn/pylsp-mypy/blob/10cbf6b5574f49c4de4da48bb0055d5249930259/test/test_plugin.py#L333-L356

**Comment by maerteijn** [comment]
@Richardk2n Any chance you could take a look at my last response? 😇

**Comment by Richardk2n** [comment]
Sorry for the delay.

If I understood correctly, what you implemented basically treats the pattern as a raw string?

This enables Windows users to just type Windows paths (while experienced users might incorrectly type the 4 \\). This is good.

However, projects working on both Linux and Windows would need to specify each path twice with this solution, or did I misunderstand?

**Comment by maerteijn** [comment]
> However, projects working on both Linux and Windows would need to specify each path twice with this solution

Good point.

 I’d better implement this as you suggested earlier. This is also the way mypy implenented it: https://github.com/python/mypy/blob/bc591c756a453bb6a78a31e734b1f0aa475e90e0/mypy/modulefinder.py#L635

PR will be updated again soon 😉

**Comment by maerteijn** [comment]
Ok, updated the logic now that you can specify patterns with forward slashes `/` and that these work on both windows as any unix variant:
```python
def match_exclude_patterns(document_path: str, exclude_patterns: list) -> bool:
    document_path = document_path.replace(os.sep, "/")

    for pattern in exclude_patterns:
        try:
            if re.search(pattern, document_path):
                log.debug(f"{document_path} matches " f"exclude pattern '{pattern}'")
                return True
        except re.error as e:
            log.error(f"pattern {pattern} is not a valid regular expression: {e}")

    return False
```

I also updated the unit test which now patches `os.path` so this test is deterministic, independent of the testrunner os.

Bonus commit: mypy 1.7 was released with this PR: https://github.com/python/mypy/pull/15996

Which means that
```python
TYPE_ERR_MSG = '"Dict[<nothing>, <nothing>]" has no attribute "append"'
```
changed into
```python
TYPE_ERR_MSG = '"Dict[Never, Never]" has no attribute "append"'
```

I converted this into a regex so we support all versions of mypy.

**Pull request merged**
